### ISSUE TITLE
Verify email link 404

### ISSUE THREAD

**Issue by tfrevert** [bitcart/bitcart-admin#201]
When an email verification link is sent using the one domain mode configuration, the link in the email is incorrect. 

Example: 
- The user clicks on resend verification and enters their email on https://my.domain.com/admin/login/email
- Email is sent. 
- Clicking on the link from the email sends the user to https://my.domain.com/login/email?code=acFhTTJecLWUjHiJrEVcTDnRFuyZAWSC instead of https://my.domain.com/admin/login/email?code=acFhTTJecLWUjHiJrEVcTDnRFuyZAWSC.

**Comment by MrNaif2018** [comment]
Hi, could you please check with latest master?
I think this commit https://github.com/bitcart/bitcart/commit/0d4cd90be000c1e068f895ed13cc7c4135bb492c
should have fixed it
sorry for delay

**Comment by MrNaif2018** [comment]
Assuming the issue is fixed, if not please re-open or post in our community chats
